### PR TITLE
Import Watts tests

### PR DESCRIPTION
**Pull request by jerhard**
This PR imports the tests from the [Watts repository](https://github.com/markus-kusano/watts/tree/master/test), which seem to be the ones used for [this paper](https://dl.acm.org/doi/pdf/10.1145/2950290.2950291?casa_token=_2R3lZv8PPMAAAAA:HJMrmgA9klU5EYJVR3Pn8b3IRybn57GqLxrMyl8jO4Fq9MeeYRTR-Zk247fcVZBi2WWfV2wV0vbBgA): _Flow-sensitive composition of thread-modular abstract interpretation_. Kusano and Wang.

The benchmark script is executed with `update_bench_traces_rel_watts.rb`.

TODO:
- [x] Check whether some of the `assert(0)`s should actually be reachable. 
- [x] Remove duplicates:
    Most example programs seem to be duplicated, where in the second version the `include <assert.h>` is commented out.

### CODE REVIEW

**Comment by sim642** [comment]
Their smaller non-DDVerify benchmarks come from SV-COMP and I do recall seeing similar ones there, when searching for benchmarks. Since they're largely boolean flag based (and use these to model locks, etc), we obviously won't be able to solve them with just Apron. Looks like they used Z3, which can handle logical relations for them.
But given that those are smaller compared to the DDVerify ones (where it sounds like we are more successful), the overall total we can prove might be quite good still, no?

**Comment by jerhard** [comment]
The test case `wdt977_02/main.c` were we have 30 failing asserts is actually broken. 
The assert we report as failing is the following:
[wdt977_02/main.c](https://github.com/goblint/bench/blob/d80bb6c3d3f123b871cf7d7f5c22b86c41744afc/watts/wdt977_02/main.c#L302-L304).
The intention most likely was to have a guarded `assert(0)`. But the `if` is followed by a semicolon, so the `assert` is actually not guarded at all.

**Comment by jerhard** [comment]
> But given that those are smaller compared to the DDVerify ones (where it sounds like we are more successful), the overall total we can prove might be quite good still, no?

Yes, we have failing/unknown assert on 16 out of the 96 benchmarks and succeed on the other 80. And for 5 of those, it is not ensured in the concrete that the `assert` will succeed.

**Comment by sim642** [comment]
Is there anything to still do here or can we merge this such that all the relational traces benchmarks are finally together in one place?

**Pull request merged**
