### PR TITLE
Incremental benchmarking script and suite

### PR DESCRIPTION
**Pull request by vesalvojdani**
This is a hacky first version of a script that does more or less what I want. The final version will be just as hacky, but it should also allow all these different flags to be compared and maybe integrate the precision comparison from the other script. The critical thing at this stage is to have some way to sanity check performance issues to determine the viability of this approach. 

Still a few things to do here:
- [x] Fix it to work on non-kernel benchmarks.
- [x] Update the readme with the instructions that I had dumped here.
- [x] Set the proper parameters for the interactive branch
- [x] Incorporate the precision comparison.
- [x] Finalize the initial benchmark suite.

Some post-finalization steps:
- [x] Display if incremental has something that is incomparable, more precise, or less.
- [x] Add some restart-needing examples in separate directory.
- [x] Run this stupid thing with intervals...
- [x] Try to add some diffs to previous benchmarks that need a restart.

### CODE REVIEW

**Comment by vesalvojdani** [comment]
So there's not really a need to "review" this, but I wanted to add some explanation of how to use it somewhere. I will maybe move this into the readme file for this repo. Might be good to have some more explanations of what all the different things are in this repo. But there are many scripts here, and I don't know what half of them are for... :)

**Comment by vogler** [comment]
I'm using the following:
- [parallel-run.sh](https://github.com/goblint/bench/blob/2d8bc2c8cb2cd6499733c535b868643f45bcae49/parallel-run.sh) to run the config in that script in parallel and log each program
- [csv-results.ml](https://github.com/goblint/bench/blob/2d8bc2c8cb2cd6499733c535b868643f45bcae49/csv-results.ml) to extract some numbers from each log and print a csv of it
- [precision.sh](https://github.com/goblint/bench/blob/2d8bc2c8cb2cd6499733c535b868643f45bcae49/precision.sh) to let goblint compare two variants for each program and write the result to a .precision file

The other (old) scripts can probably be removed.

Copying the csv to LibreOffice to get some ratios/graphs is a bit annoying, but not sure if it's worth generating something since it depends on the benchmark.

**Comment by vesalvojdani** [comment]
We can let the renaming ids serve as baseline. It makes no significant difference to the [run time](https://kodu.ut.ee/~vesal/results/211019-rename/). Something is very fishy with my comparison script or with the benchmarks because currently it seems to imply that we compute exactly the same values even without restart: [results](https://kodu.ut.ee/~vesal/results/211019-incremental/). At least, I thought [this patch](https://kodu.ut.ee/~vesal/results/211019-incremental/ypbind_comb03.patch) would result in a change in protected mutexes for a specific global. I will have to look into this.

**Comment by vesalvojdani** [comment]
Okay, running with intervals enable doesn't change the story much: [results](https://kodu.ut.ee/~vesal/results/211020-incremental). There was an incomparable thing before as well, but now there is a verification failure with `Difference: Dead code instead of bot`...

**Comment by vesalvojdani** [comment]
This is now a fairly good initial benchmark set. With Interval analysis turned on there are examples where precision is lost without restarting, but right now too much gets restarted. It is very fishy because even diffs that should not change anything globally results in restarts. Also, earlyglobs does not help.

**Pull request merged**
